### ISSUE TITLE
Do it buffer based not global based

### ISSUE THREAD

**Issue by gunar** [jaawerth/nrun.vim#1]
This: https://github.com/benekastah/neomake/issues/247#issuecomment-214714832

> @jaawerth Because you're doing let g: it's setting the option globally; you probably only want it buffer based (so different projects can use different versions of eslint), via let b: - e.g. https://github.com/benjie/neomake-local-eslint.vim/blob/master/ftplugin/javascript.vim

Thank you!!!

**Comment by jaawerth** [comment]
I think he more meant the ftplugin for Neomake + eslint on that one, since this particular plugin just gives you the "Which" and "Exec" functions with `npm-which` behavior, but now that you mention it, I shouldn't make the two options I have here (disabling fallback to "which" and overriding the "which" executable, the later of which would only be useful for windows or other non-UNIX shells AFAIK) global only, so I'll adjust in both places.

Thanks!

**Comment by gunar** [comment]
Oh, you're right. Sorry and thanks!

**Comment by jaawerth** [comment]
Updated! The fallback behavior can now be overridden with a second argument to the functions (`0` to disable the fallback to `which` or a string to change the fallback command) as an alternative to setting global options.
